project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
  resources:
    - "assets/"
  preview:
    port: 4321
    browser: true
    watch-inputs: false
execute:
  freeze: auto   # Re-render only when source changes
  echo: true #Include the source code in output
  message: false # don't show messages
  warning: false #don't include warnings in the output
  output: true #include the results of executing the code
  cache: false # don't cache code junks by default
description-meta: "Dante Yasui's personal website."
editor: 
  markdown: 
    wrap: sentence
engine: knitr
filters:
   - include-code-files

website:
  title: "Dante Yasui"
  site-url: "https://www.danteyasui.org"
  repo-url: https://github.com/dyasui/dyasui.github.io
  description: "Dante's Website"
  favicon: /assets/icon.png 
  search: true
  navbar:
    background: "#99ccff"
    logo: /assets/icon.png
    left:
      - text: "About"
        file: about.qmd
      - text: "Research"
        file: research.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Other"
        file: other.qmd
  page-footer:
    left: |
      {{< fa regular copyright >}} Dante Yasui, 2025<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)<br>
      Opinions are my own and do not represent my employer
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [{{< fa brands github >}} Source](https://github.com/dyasui/dyasui.github.io)
format:
  html:
    include-after-body: files/webex.js    
    code-fold: false
    #embed-resources: true	
    #self-contained: true
    theme: 
      light: [matria,files/customstyle.scss]
      dark: [slate,files/customstyle.scss]
    # css: files/webex.css
    toc: true
    
