---
title: "Dante Yasui, CV"
toc: true
toc-location: left
---

<head>
<script>
  document.title = "Dante Yasui: CV";
</script>
</head>

[PDF](_latex/dante-cv.pdf){.btn .btn-outline-primary .btn role="button"}

## Education

  - Ph.D. Economics, University of Oregon, 2026 (expected)
Committee: Jonathan Davis, Mark Colas, Ed Rubin, Isabel Garcıa Valdivia

  - M.S. Economics, University of Oregon, 2023

  - B.A., Lewis & Clark College, 2021

__Primary interests__: Economic History, Migration, Urban Economics
<br>

## Job Market Paper

"Forced Removal or Moved to Opportunity? Labor Market and Migration Effects of Japanese Internment"
[Draft](research/internee-outcomes/InterneeOutcomes-20251017.pdf)
<br>

## Research in progress

"Dust Bowl Migrants: Did moving across space lead to moving up the economic ladder?"
<br>

"Ethnic Enclaves and the Legacy of Internment"
<br>

## Teaching

__[EC327: Introduction to Game Theory](https://dyasui.github.io/EC327/)__

- University of Oregon: **Fall 2025**, **Winter 2024**, **Fall 2024**

__[EC311: Intermediate Microeconomic Theory](https://dyasui.github.io/EC-311/)__

- University of Oregon: **Spring 2025**

__[EC320: Introduction to Econometrics I](https://github.com/dyasui/EC320Su24)__

- University of Oregon: **Summer 2024**

## Grants, awards, etc.

Graduate Teacing Fellowship, 2021-

Kleinsorge Summer Research Fellowship, 2023

### Additional

- Graduate Brownbag Coordinator, University of Oregon, 2021-2022
- Applied Microeconomics Brownbag Coordinator, University of Oregon, 2022-2023

## Skills

- __Computing:__ R, QGIS, ArcGIS, Julia, Python
- __Writing/Office:__ LaTeX, Quarto, Microsoft 365

## Contact

- __email__ dyasui@uoregon.edu
- __website__ [danteyasui.org](http://danteyasui.org)
- __github__ [dyasui](https://github.com/dyasui)
