# Instructor of Record


## [EC327: Introduction to Game Theory](https://dyasui.github.io/EC327/)

Term: **Fall 2025**, **Winter 2024**, **Fall 2024** (80 student cap)

Class website: <https://dyasui.github.io/EC327>

Course materials repository: <https://github.com/dyasui/EC327>

### Selected Student Feedback

- "Dante is a great professor who very obviously cares about us an wants us to succeed. Always made sure to set up additional office hours with me so I could understand the material which was really appreciated."

- "I really like Dante's teaching styles and interactive learning"

## [EC311: Intermediate Microeconomic Theory](https://dyasui.github.io/EC-311/)

Term: **Spring 2025** (93 students)

Class website: <https://dyasui.github.io/EC-311>

Course materials repository: <https://github.com/dyasui/EC-311>

### Selected Student Feedback

- "Dante is very supportive in situations whether that be tech issues, confusion on the work, or just meeting outside of class/office hours. His support made this hard class slightly easier."

- "I think Dante did a great job at trying multiple strategies to make the content easy to digest."

- "I really appreciate how this course was organized. Dante made a course website with all the material needed for the course, which was super easy to access. It had practice problems, slides, and practice exams to try and prepare us for the course."

## [EC320: Introduction to Econometrics I](https://github.com/dyasui/EC320Su24)

Term: **Summer 2024** (12 students, asynchronous)

Course materials repository: <https://github.com/dyasui/EC320Su24>

### Selected Student Feedback

- "The assignments were well designed, lectures were informative, feedback was thorough, content is extremely relevant, expectations were clear. Great class."

--- 

# Teaching Assistant

### EC201 Introduction to Microeconomics 
(Fall 2021)

Discussion Leader

### EC202 Introduction to Macroeconomics 
(Winter 2021, Spring 2022)

Discussion Leader

### EC411/511 Advanced Microeconomic Theory 
(Fall 2022)

Graded homework, assisted with student questions during in-class activities, held office hours

### EC327 Introduction to Game Theory 
(Fall 2022, Spring 2023, Fall 2023)

Graded homework and exams

### EC350 Labor Market Issues 
(Spring 2023)

Graded homework and exams

### EC320 Introduction to Econometrics I 
(Fall 2023, Spring 2024)

Assisted with in-class activities, and additional lab sections
